### ISSUE TITLE
Better way to add bootstrap?

### ISSUE THREAD

**Issue by massimilianomarini** [kadira-samples/meteor-data-and-react#2]
Hi @arunoda,

this sample app is simply great! Good work! :+1: 

What is the best way to install `bootstrap` with the new coming Meteor 1.3?

```
meteor add twbs:bootstrap
```

or

```
npm install --save bootstrap
```

**Comment by arunoda** [comment]
I think it's still the the meteor package since there is no way we can get CSS from NPM modules yet.

**Comment by massimilianomarini** [comment]
Ok thanks! :)
